
package org.wattalyst.services.secured;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SecuredDRSignalManagement", targetNamespace = "http://secured.services.wattalyst.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SecuredDRSignalManagement {


    /**
     * 
     * @param description
     * @param value
     * @param authenticationToken
     * @param locationname
     * @param successStatus
     * @param signalId
     * @return
     *     returns org.wattalyst.services.secured.BooleanResultContainer
     */
    @WebMethod
    @WebResult(name = "booleanResultContainer", targetNamespace = "")
    @RequestWrapper(localName = "setPerformanceIndicator", targetNamespace = "http://secured.services.wattalyst.org/", className = "org.wattalyst.services.secured.SetPerformanceIndicator")
    @ResponseWrapper(localName = "setPerformanceIndicatorResponse", targetNamespace = "http://secured.services.wattalyst.org/", className = "org.wattalyst.services.secured.SetPerformanceIndicatorResponse")
    @Action(input = "http://secured.services.wattalyst.org/SecuredDRSignalManagement/setPerformanceIndicatorRequest", output = "http://secured.services.wattalyst.org/SecuredDRSignalManagement/setPerformanceIndicatorResponse")
    public BooleanResultContainer setPerformanceIndicator(
        @WebParam(name = "authenticationToken", targetNamespace = "")
        String authenticationToken,
        @WebParam(name = "signalId", targetNamespace = "")
        String signalId,
        @WebParam(name = "locationname", targetNamespace = "")
        String locationname,
        @WebParam(name = "value", targetNamespace = "")
        Double value,
        @WebParam(name = "description", targetNamespace = "")
        String description,
        @WebParam(name = "successStatus", targetNamespace = "")
        String successStatus);

    /**
     * 
     * @param authenticationToken
     * @param locationname
     * @param signalId
     * @return
     *     returns org.wattalyst.services.secured.FeedbackResultContainer
     */
    @WebMethod
    @WebResult(name = "feedbackResultContainer", targetNamespace = "")
    @RequestWrapper(localName = "getUserFeedbackForLocation", targetNamespace = "http://secured.services.wattalyst.org/", className = "org.wattalyst.services.secured.GetUserFeedbackForLocation")
    @ResponseWrapper(localName = "getUserFeedbackForLocationResponse", targetNamespace = "http://secured.services.wattalyst.org/", className = "org.wattalyst.services.secured.GetUserFeedbackForLocationResponse")
    @Action(input = "http://secured.services.wattalyst.org/SecuredDRSignalManagement/getUserFeedbackForLocationRequest", output = "http://secured.services.wattalyst.org/SecuredDRSignalManagement/getUserFeedbackForLocationResponse")
    public FeedbackResultContainer getUserFeedbackForLocation(
        @WebParam(name = "authenticationToken", targetNamespace = "")
        String authenticationToken,
        @WebParam(name = "signalId", targetNamespace = "")
        String signalId,
        @WebParam(name = "locationname", targetNamespace = "")
        String locationname);

    /**
     * 
     * @param authenticationToken
     * @param locationname
     * @param acceptanceStatus
     * @param signalId
     * @return
     *     returns org.wattalyst.services.secured.BooleanResultContainer
     */
    @WebMethod
    @WebResult(name = "booleanResultContainer", targetNamespace = "")
    @RequestWrapper(localName = "setAcceptanceStatus", targetNamespace = "http://secured.services.wattalyst.org/", className = "org.wattalyst.services.secured.SetAcceptanceStatus")
    @ResponseWrapper(localName = "setAcceptanceStatusResponse", targetNamespace = "http://secured.services.wattalyst.org/", className = "org.wattalyst.services.secured.SetAcceptanceStatusResponse")
    @Action(input = "http://secured.services.wattalyst.org/SecuredDRSignalManagement/setAcceptanceStatusRequest", output = "http://secured.services.wattalyst.org/SecuredDRSignalManagement/setAcceptanceStatusResponse")
    public BooleanResultContainer setAcceptanceStatus(
        @WebParam(name = "authenticationToken", targetNamespace = "")
        String authenticationToken,
        @WebParam(name = "signalId", targetNamespace = "")
        String signalId,
        @WebParam(name = "locationname", targetNamespace = "")
        String locationname,
        @WebParam(name = "acceptanceStatus", targetNamespace = "")
        String acceptanceStatus);

    /**
     * 
     * @param eventStatuses
     * @param authenticationToken
     * @return
     *     returns org.wattalyst.services.secured.DrSignalListResultContainer
     */
    @WebMethod
    @WebResult(name = "drSignalListResultContainer", targetNamespace = "")
    @RequestWrapper(localName = "getDRSignalsByEventStatuses", targetNamespace = "http://secured.services.wattalyst.org/", className = "org.wattalyst.services.secured.GetDRSignalsByEventStatuses")
    @ResponseWrapper(localName = "getDRSignalsByEventStatusesResponse", targetNamespace = "http://secured.services.wattalyst.org/", className = "org.wattalyst.services.secured.GetDRSignalsByEventStatusesResponse")
    @Action(input = "http://secured.services.wattalyst.org/SecuredDRSignalManagement/getDRSignalsByEventStatusesRequest", output = "http://secured.services.wattalyst.org/SecuredDRSignalManagement/getDRSignalsByEventStatusesResponse")
    public DrSignalListResultContainer getDRSignalsByEventStatuses(
        @WebParam(name = "authenticationToken", targetNamespace = "")
        String authenticationToken,
        @WebParam(name = "eventStatuses", targetNamespace = "")
        List<String> eventStatuses);

    /**
     * 
     * @param startDate
     * @param baslineId
     * @param authenticationToken
     * @param endDate
     * @return
     *     returns org.wattalyst.services.secured.ValueListResultContainer
     */
    @WebMethod
    @WebResult(name = "valueListResultContainer", targetNamespace = "")
    @RequestWrapper(localName = "getBaselineData", targetNamespace = "http://secured.services.wattalyst.org/", className = "org.wattalyst.services.secured.GetBaselineData")
    @ResponseWrapper(localName = "getBaselineDataResponse", targetNamespace = "http://secured.services.wattalyst.org/", className = "org.wattalyst.services.secured.GetBaselineDataResponse")
    @Action(input = "http://secured.services.wattalyst.org/SecuredDRSignalManagement/getBaselineDataRequest", output = "http://secured.services.wattalyst.org/SecuredDRSignalManagement/getBaselineDataResponse")
    public ValueListResultContainer getBaselineData(
        @WebParam(name = "authenticationToken", targetNamespace = "")
        String authenticationToken,
        @WebParam(name = "baslineId", targetNamespace = "")
        String baslineId,
        @WebParam(name = "startDate", targetNamespace = "")
        long startDate,
        @WebParam(name = "endDate", targetNamespace = "")
        long endDate);

    /**
     * 
     * @param baselineId
     * @param values
     * @param authenticationToken
     * @return
     *     returns org.wattalyst.services.secured.BooleanResultContainer
     */
    @WebMethod
    @WebResult(name = "booleanResultContainer", targetNamespace = "")
    @RequestWrapper(localName = "uploadBaselineData", targetNamespace = "http://secured.services.wattalyst.org/", className = "org.wattalyst.services.secured.UploadBaselineData")
    @ResponseWrapper(localName = "uploadBaselineDataResponse", targetNamespace = "http://secured.services.wattalyst.org/", className = "org.wattalyst.services.secured.UploadBaselineDataResponse")
    @Action(input = "http://secured.services.wattalyst.org/SecuredDRSignalManagement/uploadBaselineDataRequest", output = "http://secured.services.wattalyst.org/SecuredDRSignalManagement/uploadBaselineDataResponse")
    public BooleanResultContainer uploadBaselineData(
        @WebParam(name = "authenticationToken", targetNamespace = "")
        String authenticationToken,
        @WebParam(name = "baselineId", targetNamespace = "")
        String baselineId,
        @WebParam(name = "values", targetNamespace = "")
        String values);

    /**
     * 
     * @param sensorReference
     * @param description
     * @param authenticationToken
     * @param baselineType
     * @return
     *     returns org.wattalyst.services.secured.StringResultContainer
     */
    @WebMethod
    @WebResult(name = "stringResultContainer", targetNamespace = "")
    @RequestWrapper(localName = "addBaseline", targetNamespace = "http://secured.services.wattalyst.org/", className = "org.wattalyst.services.secured.AddBaseline")
    @ResponseWrapper(localName = "addBaselineResponse", targetNamespace = "http://secured.services.wattalyst.org/", className = "org.wattalyst.services.secured.AddBaselineResponse")
    @Action(input = "http://secured.services.wattalyst.org/SecuredDRSignalManagement/addBaselineRequest", output = "http://secured.services.wattalyst.org/SecuredDRSignalManagement/addBaselineResponse")
    public StringResultContainer addBaseline(
        @WebParam(name = "authenticationToken", targetNamespace = "")
        String authenticationToken,
        @WebParam(name = "description", targetNamespace = "")
        String description,
        @WebParam(name = "baselineType", targetNamespace = "")
        String baselineType,
        @WebParam(name = "sensorReference", targetNamespace = "")
        String sensorReference);

    /**
     * 
     * @param sensorReference
     * @param authenticationToken
     * @return
     *     returns org.wattalyst.services.secured.BaselineListResultContainer
     */
    @WebMethod
    @WebResult(name = "baselineListResultContainer", targetNamespace = "")
    @RequestWrapper(localName = "getBaselines", targetNamespace = "http://secured.services.wattalyst.org/", className = "org.wattalyst.services.secured.GetBaselines")
    @ResponseWrapper(localName = "getBaselinesResponse", targetNamespace = "http://secured.services.wattalyst.org/", className = "org.wattalyst.services.secured.GetBaselinesResponse")
    @Action(input = "http://secured.services.wattalyst.org/SecuredDRSignalManagement/getBaselinesRequest", output = "http://secured.services.wattalyst.org/SecuredDRSignalManagement/getBaselinesResponse")
    public BaselineListResultContainer getBaselines(
        @WebParam(name = "authenticationToken", targetNamespace = "")
        String authenticationToken,
        @WebParam(name = "sensorReference", targetNamespace = "")
        String sensorReference);

    /**
     * 
     * @param authenticationToken
     * @return
     *     returns org.wattalyst.services.secured.DrUseCaseListResultContainer
     */
    @WebMethod
    @WebResult(name = "useCaseListResultContainer", targetNamespace = "")
    @RequestWrapper(localName = "getAllDRUseCases", targetNamespace = "http://secured.services.wattalyst.org/", className = "org.wattalyst.services.secured.GetAllDRUseCases")
    @ResponseWrapper(localName = "getAllDRUseCasesResponse", targetNamespace = "http://secured.services.wattalyst.org/", className = "org.wattalyst.services.secured.GetAllDRUseCasesResponse")
    @Action(input = "http://secured.services.wattalyst.org/SecuredDRSignalManagement/getAllDRUseCasesRequest", output = "http://secured.services.wattalyst.org/SecuredDRSignalManagement/getAllDRUseCasesResponse")
    public DrUseCaseListResultContainer getAllDRUseCases(
        @WebParam(name = "authenticationToken", targetNamespace = "")
        String authenticationToken);

    /**
     * 
     * @param authenticationToken
     * @param signalId
     * @return
     *     returns org.wattalyst.services.secured.BooleanResultContainer
     */
    @WebMethod
    @WebResult(name = "booleanResultContainer", targetNamespace = "")
    @RequestWrapper(localName = "cancelSignal", targetNamespace = "http://secured.services.wattalyst.org/", className = "org.wattalyst.services.secured.CancelSignal")
    @ResponseWrapper(localName = "cancelSignalResponse", targetNamespace = "http://secured.services.wattalyst.org/", className = "org.wattalyst.services.secured.CancelSignalResponse")
    @Action(input = "http://secured.services.wattalyst.org/SecuredDRSignalManagement/cancelSignalRequest", output = "http://secured.services.wattalyst.org/SecuredDRSignalManagement/cancelSignalResponse")
    public BooleanResultContainer cancelSignal(
        @WebParam(name = "authenticationToken", targetNamespace = "")
        String authenticationToken,
        @WebParam(name = "signalId", targetNamespace = "")
        String signalId);

    /**
     * 
     * @param fullQualifiedName
     * @param authenticationToken
     * @return
     *     returns org.wattalyst.services.secured.StringResultContainer
     */
    @WebMethod
    @WebResult(name = "stringResultContainer", targetNamespace = "")
    @RequestWrapper(localName = "storeAndActivateSignal", targetNamespace = "http://secured.services.wattalyst.org/", className = "org.wattalyst.services.secured.StoreAndActivateSignal")
    @ResponseWrapper(localName = "storeAndActivateSignalResponse", targetNamespace = "http://secured.services.wattalyst.org/", className = "org.wattalyst.services.secured.StoreAndActivateSignalResponse")
    @Action(input = "http://secured.services.wattalyst.org/SecuredDRSignalManagement/storeAndActivateSignalRequest", output = "http://secured.services.wattalyst.org/SecuredDRSignalManagement/storeAndActivateSignalResponse")
    public StringResultContainer storeAndActivateSignal(
        @WebParam(name = "authenticationToken", targetNamespace = "")
        String authenticationToken,
        @WebParam(name = "fullQualifiedName", targetNamespace = "")
        String fullQualifiedName);

    /**
     * 
     * @param authenticationToken
     * @param locationname
     * @param acceptanceStatus
     * @return
     *     returns org.wattalyst.services.secured.StringListResultContainer
     */
    @WebMethod
    @WebResult(name = "stringListResultContainer", targetNamespace = "")
    @RequestWrapper(localName = "getSignalIdsByAcceptanceStatus", targetNamespace = "http://secured.services.wattalyst.org/", className = "org.wattalyst.services.secured.GetSignalIdsByAcceptanceStatus")
    @ResponseWrapper(localName = "getSignalIdsByAcceptanceStatusResponse", targetNamespace = "http://secured.services.wattalyst.org/", className = "org.wattalyst.services.secured.GetSignalIdsByAcceptanceStatusResponse")
    @Action(input = "http://secured.services.wattalyst.org/SecuredDRSignalManagement/getSignalIdsByAcceptanceStatusRequest", output = "http://secured.services.wattalyst.org/SecuredDRSignalManagement/getSignalIdsByAcceptanceStatusResponse")
    public StringListResultContainer getSignalIdsByAcceptanceStatus(
        @WebParam(name = "authenticationToken", targetNamespace = "")
        String authenticationToken,
        @WebParam(name = "locationname", targetNamespace = "")
        String locationname,
        @WebParam(name = "acceptanceStatus", targetNamespace = "")
        List<String> acceptanceStatus);

    /**
     * 
     * @param authenticationToken
     * @param locationname
     * @param signalId
     * @return
     *     returns org.wattalyst.services.secured.DrSignalResultContainer
     */
    @WebMethod
    @WebResult(name = "drSignalResultContainer", targetNamespace = "")
    @RequestWrapper(localName = "getDetailsByLocationAndDRSignalId", targetNamespace = "http://secured.services.wattalyst.org/", className = "org.wattalyst.services.secured.GetDetailsByLocationAndDRSignalId")
    @ResponseWrapper(localName = "getDetailsByLocationAndDRSignalIdResponse", targetNamespace = "http://secured.services.wattalyst.org/", className = "org.wattalyst.services.secured.GetDetailsByLocationAndDRSignalIdResponse")
    @Action(input = "http://secured.services.wattalyst.org/SecuredDRSignalManagement/getDetailsByLocationAndDRSignalIdRequest", output = "http://secured.services.wattalyst.org/SecuredDRSignalManagement/getDetailsByLocationAndDRSignalIdResponse")
    public DrSignalResultContainer getDetailsByLocationAndDRSignalId(
        @WebParam(name = "authenticationToken", targetNamespace = "")
        String authenticationToken,
        @WebParam(name = "locationname", targetNamespace = "")
        String locationname,
        @WebParam(name = "signalId", targetNamespace = "")
        String signalId);

    /**
     * 
     * @param authenticationToken
     * @param locationname
     * @param signalStatuses
     * @return
     *     returns org.wattalyst.services.secured.StringListResultContainer
     */
    @WebMethod
    @WebResult(name = "stringListResultContainer", targetNamespace = "")
    @RequestWrapper(localName = "getSignalIdsBySignalStatus", targetNamespace = "http://secured.services.wattalyst.org/", className = "org.wattalyst.services.secured.GetSignalIdsBySignalStatus")
    @ResponseWrapper(localName = "getSignalIdsBySignalStatusResponse", targetNamespace = "http://secured.services.wattalyst.org/", className = "org.wattalyst.services.secured.GetSignalIdsBySignalStatusResponse")
    @Action(input = "http://secured.services.wattalyst.org/SecuredDRSignalManagement/getSignalIdsBySignalStatusRequest", output = "http://secured.services.wattalyst.org/SecuredDRSignalManagement/getSignalIdsBySignalStatusResponse")
    public StringListResultContainer getSignalIdsBySignalStatus(
        @WebParam(name = "authenticationToken", targetNamespace = "")
        String authenticationToken,
        @WebParam(name = "locationname", targetNamespace = "")
        String locationname,
        @WebParam(name = "signalStatuses", targetNamespace = "")
        List<String> signalStatuses);

    /**
     * 
     * @param message
     * @param usefulness
     * @param username
     * @param convenience
     * @param authenticationToken
     * @param locationname
     * @param signalId
     * @return
     *     returns org.wattalyst.services.secured.BooleanResultContainer
     */
    @WebMethod
    @WebResult(name = "booleanResultContainer", targetNamespace = "")
    @RequestWrapper(localName = "setUserFeedback", targetNamespace = "http://secured.services.wattalyst.org/", className = "org.wattalyst.services.secured.SetUserFeedback")
    @ResponseWrapper(localName = "setUserFeedbackResponse", targetNamespace = "http://secured.services.wattalyst.org/", className = "org.wattalyst.services.secured.SetUserFeedbackResponse")
    @Action(input = "http://secured.services.wattalyst.org/SecuredDRSignalManagement/setUserFeedbackRequest", output = "http://secured.services.wattalyst.org/SecuredDRSignalManagement/setUserFeedbackResponse")
    public BooleanResultContainer setUserFeedback(
        @WebParam(name = "authenticationToken", targetNamespace = "")
        String authenticationToken,
        @WebParam(name = "signalId", targetNamespace = "")
        String signalId,
        @WebParam(name = "locationname", targetNamespace = "")
        String locationname,
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "usefulness", targetNamespace = "")
        Integer usefulness,
        @WebParam(name = "convenience", targetNamespace = "")
        Integer convenience,
        @WebParam(name = "message", targetNamespace = "")
        String message);

    /**
     * 
     * @param authenticationToken
     * @param locationname
     * @return
     *     returns org.wattalyst.services.secured.DrSignalListResultContainer
     */
    @WebMethod
    @WebResult(name = "drSignalListResultContainer", targetNamespace = "")
    @RequestWrapper(localName = "getNewDRSignalByLocation", targetNamespace = "http://secured.services.wattalyst.org/", className = "org.wattalyst.services.secured.GetNewDRSignalByLocation")
    @ResponseWrapper(localName = "getNewDRSignalByLocationResponse", targetNamespace = "http://secured.services.wattalyst.org/", className = "org.wattalyst.services.secured.GetNewDRSignalByLocationResponse")
    @Action(input = "http://secured.services.wattalyst.org/SecuredDRSignalManagement/getNewDRSignalByLocationRequest", output = "http://secured.services.wattalyst.org/SecuredDRSignalManagement/getNewDRSignalByLocationResponse")
    public DrSignalListResultContainer getNewDRSignalByLocation(
        @WebParam(name = "authenticationToken", targetNamespace = "")
        String authenticationToken,
        @WebParam(name = "locationname", targetNamespace = "")
        String locationname);

    /**
     * 
     * @param authenticationToken
     * @param locationname
     * @param signalStatus
     * @param signalId
     * @return
     *     returns org.wattalyst.services.secured.BooleanResultContainer
     */
    @WebMethod
    @WebResult(name = "booleanResultContainer", targetNamespace = "")
    @RequestWrapper(localName = "setDRSignalStatus", targetNamespace = "http://secured.services.wattalyst.org/", className = "org.wattalyst.services.secured.SetDRSignalStatus")
    @ResponseWrapper(localName = "setDRSignalStatusResponse", targetNamespace = "http://secured.services.wattalyst.org/", className = "org.wattalyst.services.secured.SetDRSignalStatusResponse")
    @Action(input = "http://secured.services.wattalyst.org/SecuredDRSignalManagement/setDRSignalStatusRequest", output = "http://secured.services.wattalyst.org/SecuredDRSignalManagement/setDRSignalStatusResponse")
    public BooleanResultContainer setDRSignalStatus(
        @WebParam(name = "authenticationToken", targetNamespace = "")
        String authenticationToken,
        @WebParam(name = "signalId", targetNamespace = "")
        String signalId,
        @WebParam(name = "locationname", targetNamespace = "")
        String locationname,
        @WebParam(name = "signalStatus", targetNamespace = "")
        String signalStatus);

    /**
     * 
     * @param startDate
     * @param baselineId
     * @param authenticationToken
     * @param endDate
     * @return
     *     returns org.wattalyst.services.secured.StringResultContainer
     */
    @WebMethod
    @WebResult(name = "stringResultContainer", targetNamespace = "")
    @RequestWrapper(localName = "getBaselineDataAsCSV", targetNamespace = "http://secured.services.wattalyst.org/", className = "org.wattalyst.services.secured.GetBaselineDataAsCSV")
    @ResponseWrapper(localName = "getBaselineDataAsCSVResponse", targetNamespace = "http://secured.services.wattalyst.org/", className = "org.wattalyst.services.secured.GetBaselineDataAsCSVResponse")
    @Action(input = "http://secured.services.wattalyst.org/SecuredDRSignalManagement/getBaselineDataAsCSVRequest", output = "http://secured.services.wattalyst.org/SecuredDRSignalManagement/getBaselineDataAsCSVResponse")
    public StringResultContainer getBaselineDataAsCSV(
        @WebParam(name = "authenticationToken", targetNamespace = "")
        String authenticationToken,
        @WebParam(name = "baselineId", targetNamespace = "")
        String baselineId,
        @WebParam(name = "startDate", targetNamespace = "")
        long startDate,
        @WebParam(name = "endDate", targetNamespace = "")
        long endDate);

    /**
     * 
     * @param authenticationToken
     * @param locationname
     * @return
     *     returns org.wattalyst.services.secured.IntegerResultContainer
     */
    @WebMethod
    @WebResult(name = "integerResultContainer", targetNamespace = "")
    @RequestWrapper(localName = "getTotalEarnedCoinsByLocation", targetNamespace = "http://secured.services.wattalyst.org/", className = "org.wattalyst.services.secured.GetTotalEarnedCoinsByLocation")
    @ResponseWrapper(localName = "getTotalEarnedCoinsByLocationResponse", targetNamespace = "http://secured.services.wattalyst.org/", className = "org.wattalyst.services.secured.GetTotalEarnedCoinsByLocationResponse")
    @Action(input = "http://secured.services.wattalyst.org/SecuredDRSignalManagement/getTotalEarnedCoinsByLocationRequest", output = "http://secured.services.wattalyst.org/SecuredDRSignalManagement/getTotalEarnedCoinsByLocationResponse")
    public IntegerResultContainer getTotalEarnedCoinsByLocation(
        @WebParam(name = "authenticationToken", targetNamespace = "")
        String authenticationToken,
        @WebParam(name = "locationname", targetNamespace = "")
        String locationname);

    /**
     * 
     * @param authenticationToken
     * @param locationname
     * @param signalId
     * @return
     *     returns org.wattalyst.services.secured.IntegerResultContainer
     */
    @WebMethod
    @WebResult(name = "integerResultContainer", targetNamespace = "")
    @RequestWrapper(localName = "getCoinsForSignalByLocation", targetNamespace = "http://secured.services.wattalyst.org/", className = "org.wattalyst.services.secured.GetCoinsForSignalByLocation")
    @ResponseWrapper(localName = "getCoinsForSignalByLocationResponse", targetNamespace = "http://secured.services.wattalyst.org/", className = "org.wattalyst.services.secured.GetCoinsForSignalByLocationResponse")
    @Action(input = "http://secured.services.wattalyst.org/SecuredDRSignalManagement/getCoinsForSignalByLocationRequest", output = "http://secured.services.wattalyst.org/SecuredDRSignalManagement/getCoinsForSignalByLocationResponse")
    public IntegerResultContainer getCoinsForSignalByLocation(
        @WebParam(name = "authenticationToken", targetNamespace = "")
        String authenticationToken,
        @WebParam(name = "signalId", targetNamespace = "")
        String signalId,
        @WebParam(name = "locationname", targetNamespace = "")
        String locationname);

    /**
     * 
     * @param authenticationToken
     * @param locationname
     * @param signalId
     * @return
     *     returns org.wattalyst.services.secured.PiResultContainer
     */
    @WebMethod
    @WebResult(name = "piResultContainer", targetNamespace = "")
    @RequestWrapper(localName = "getPerformanceIndicator", targetNamespace = "http://secured.services.wattalyst.org/", className = "org.wattalyst.services.secured.GetPerformanceIndicator")
    @ResponseWrapper(localName = "getPerformanceIndicatorResponse", targetNamespace = "http://secured.services.wattalyst.org/", className = "org.wattalyst.services.secured.GetPerformanceIndicatorResponse")
    @Action(input = "http://secured.services.wattalyst.org/SecuredDRSignalManagement/getPerformanceIndicatorRequest", output = "http://secured.services.wattalyst.org/SecuredDRSignalManagement/getPerformanceIndicatorResponse")
    public PiResultContainer getPerformanceIndicator(
        @WebParam(name = "authenticationToken", targetNamespace = "")
        String authenticationToken,
        @WebParam(name = "signalId", targetNamespace = "")
        String signalId,
        @WebParam(name = "locationname", targetNamespace = "")
        String locationname);

    /**
     * 
     * @param authenticationToken
     * @param locationname
     * @param signalStatuses
     * @return
     *     returns org.wattalyst.services.secured.DrSignalListResultContainer
     */
    @WebMethod
    @WebResult(name = "drSignalListResultContainer", targetNamespace = "")
    @RequestWrapper(localName = "getDRSignalsByLocationAndStatuses", targetNamespace = "http://secured.services.wattalyst.org/", className = "org.wattalyst.services.secured.GetDRSignalsByLocationAndStatuses")
    @ResponseWrapper(localName = "getDRSignalsByLocationAndStatusesResponse", targetNamespace = "http://secured.services.wattalyst.org/", className = "org.wattalyst.services.secured.GetDRSignalsByLocationAndStatusesResponse")
    @Action(input = "http://secured.services.wattalyst.org/SecuredDRSignalManagement/getDRSignalsByLocationAndStatusesRequest", output = "http://secured.services.wattalyst.org/SecuredDRSignalManagement/getDRSignalsByLocationAndStatusesResponse")
    public DrSignalListResultContainer getDRSignalsByLocationAndStatuses(
        @WebParam(name = "authenticationToken", targetNamespace = "")
        String authenticationToken,
        @WebParam(name = "locationname", targetNamespace = "")
        String locationname,
        @WebParam(name = "signalStatuses", targetNamespace = "")
        List<String> signalStatuses);

    /**
     * 
     * @param authenticationToken
     * @return
     *     returns org.wattalyst.services.secured.LocationListResultContainer
     */
    @WebMethod
    @WebResult(name = "locationListResultContainer", targetNamespace = "")
    @RequestWrapper(localName = "getAccessibleLocations", targetNamespace = "http://secured.services.wattalyst.org/", className = "org.wattalyst.services.secured.GetAccessibleLocations")
    @ResponseWrapper(localName = "getAccessibleLocationsResponse", targetNamespace = "http://secured.services.wattalyst.org/", className = "org.wattalyst.services.secured.GetAccessibleLocationsResponse")
    @Action(input = "http://secured.services.wattalyst.org/SecuredDRSignalManagement/getAccessibleLocationsRequest", output = "http://secured.services.wattalyst.org/SecuredDRSignalManagement/getAccessibleLocationsResponse")
    public LocationListResultContainer getAccessibleLocations(
        @WebParam(name = "authenticationToken", targetNamespace = "")
        String authenticationToken);

    /**
     * 
     * @param authenticationToken
     * @param useCaseId
     * @return
     *     returns org.wattalyst.services.secured.DrSignalListResultContainer
     */
    @WebMethod
    @WebResult(name = "drSignalListResultContainer", targetNamespace = "")
    @RequestWrapper(localName = "getAllSignalsForUseCase", targetNamespace = "http://secured.services.wattalyst.org/", className = "org.wattalyst.services.secured.GetAllSignalsForUseCase")
    @ResponseWrapper(localName = "getAllSignalsForUseCaseResponse", targetNamespace = "http://secured.services.wattalyst.org/", className = "org.wattalyst.services.secured.GetAllSignalsForUseCaseResponse")
    @Action(input = "http://secured.services.wattalyst.org/SecuredDRSignalManagement/getAllSignalsForUseCaseRequest", output = "http://secured.services.wattalyst.org/SecuredDRSignalManagement/getAllSignalsForUseCaseResponse")
    public DrSignalListResultContainer getAllSignalsForUseCase(
        @WebParam(name = "authenticationToken", targetNamespace = "")
        String authenticationToken,
        @WebParam(name = "useCaseId", targetNamespace = "")
        String useCaseId);

    /**
     * 
     * @param authenticationToken
     * @param locationname
     * @param signalId
     * @return
     *     returns org.wattalyst.services.secured.DrSignalPerfomaceStatusResultContainer
     */
    @WebMethod
    @WebResult(name = "drSignalPerfomaceStatusResultContainer", targetNamespace = "")
    @RequestWrapper(localName = "getDRSignalPerformanceStatus", targetNamespace = "http://secured.services.wattalyst.org/", className = "org.wattalyst.services.secured.GetDRSignalPerformanceStatus")
    @ResponseWrapper(localName = "getDRSignalPerformanceStatusResponse", targetNamespace = "http://secured.services.wattalyst.org/", className = "org.wattalyst.services.secured.GetDRSignalPerformanceStatusResponse")
    @Action(input = "http://secured.services.wattalyst.org/SecuredDRSignalManagement/getDRSignalPerformanceStatusRequest", output = "http://secured.services.wattalyst.org/SecuredDRSignalManagement/getDRSignalPerformanceStatusResponse")
    public DrSignalPerfomaceStatusResultContainer getDRSignalPerformanceStatus(
        @WebParam(name = "authenticationToken", targetNamespace = "")
        String authenticationToken,
        @WebParam(name = "signalId", targetNamespace = "")
        String signalId,
        @WebParam(name = "locationname", targetNamespace = "")
        String locationname);

    /**
     * 
     * @param startTime
     * @param location
     * @param authenticationToken
     * @param endTime
     * @return
     *     returns org.wattalyst.services.secured.DrSignalListResultContainer
     */
    @WebMethod
    @WebResult(name = "drSignalListResultContainer", targetNamespace = "")
    @RequestWrapper(localName = "getSignalDetailsForLocationInInterval", targetNamespace = "http://secured.services.wattalyst.org/", className = "org.wattalyst.services.secured.GetSignalDetailsForLocationInInterval")
    @ResponseWrapper(localName = "getSignalDetailsForLocationInIntervalResponse", targetNamespace = "http://secured.services.wattalyst.org/", className = "org.wattalyst.services.secured.GetSignalDetailsForLocationInIntervalResponse")
    @Action(input = "http://secured.services.wattalyst.org/SecuredDRSignalManagement/getSignalDetailsForLocationInIntervalRequest", output = "http://secured.services.wattalyst.org/SecuredDRSignalManagement/getSignalDetailsForLocationInIntervalResponse")
    public DrSignalListResultContainer getSignalDetailsForLocationInInterval(
        @WebParam(name = "authenticationToken", targetNamespace = "")
        String authenticationToken,
        @WebParam(name = "startTime", targetNamespace = "")
        long startTime,
        @WebParam(name = "endTime", targetNamespace = "")
        long endTime,
        @WebParam(name = "location", targetNamespace = "")
        String location);

    /**
     * 
     * @param authenticationToken
     * @param locationname
     * @param signalId
     * @return
     *     returns org.wattalyst.services.secured.BooleanResultContainer
     */
    @WebMethod
    @WebResult(name = "booleanResultContainer", targetNamespace = "")
    @RequestWrapper(localName = "cancelSignalForLocation", targetNamespace = "http://secured.services.wattalyst.org/", className = "org.wattalyst.services.secured.CancelSignalForLocation")
    @ResponseWrapper(localName = "cancelSignalForLocationResponse", targetNamespace = "http://secured.services.wattalyst.org/", className = "org.wattalyst.services.secured.CancelSignalForLocationResponse")
    @Action(input = "http://secured.services.wattalyst.org/SecuredDRSignalManagement/cancelSignalForLocationRequest", output = "http://secured.services.wattalyst.org/SecuredDRSignalManagement/cancelSignalForLocationResponse")
    public BooleanResultContainer cancelSignalForLocation(
        @WebParam(name = "authenticationToken", targetNamespace = "")
        String authenticationToken,
        @WebParam(name = "signalId", targetNamespace = "")
        String signalId,
        @WebParam(name = "locationname", targetNamespace = "")
        String locationname);

    /**
     * 
     * @param authenticationToken
     * @param signalId
     * @return
     *     returns org.wattalyst.services.secured.TaskListResultContainer
     */
    @WebMethod
    @WebResult(name = "taskListResultContainer", targetNamespace = "")
    @RequestWrapper(localName = "getTaskDefinitions", targetNamespace = "http://secured.services.wattalyst.org/", className = "org.wattalyst.services.secured.GetTaskDefinitions")
    @ResponseWrapper(localName = "getTaskDefinitionsResponse", targetNamespace = "http://secured.services.wattalyst.org/", className = "org.wattalyst.services.secured.GetTaskDefinitionsResponse")
    @Action(input = "http://secured.services.wattalyst.org/SecuredDRSignalManagement/getTaskDefinitionsRequest", output = "http://secured.services.wattalyst.org/SecuredDRSignalManagement/getTaskDefinitionsResponse")
    public TaskListResultContainer getTaskDefinitions(
        @WebParam(name = "authenticationToken", targetNamespace = "")
        String authenticationToken,
        @WebParam(name = "signalId", targetNamespace = "")
        String signalId);

    /**
     * 
     * @param username
     * @param passwordHash
     * @return
     *     returns org.wattalyst.services.secured.StringResultContainer
     */
    @WebMethod
    @WebResult(name = "authenticationToken", targetNamespace = "")
    @RequestWrapper(localName = "login", targetNamespace = "http://secured.services.wattalyst.org/", className = "org.wattalyst.services.secured.Login")
    @ResponseWrapper(localName = "loginResponse", targetNamespace = "http://secured.services.wattalyst.org/", className = "org.wattalyst.services.secured.LoginResponse")
    @Action(input = "http://secured.services.wattalyst.org/SecuredDRSignalManagement/loginRequest", output = "http://secured.services.wattalyst.org/SecuredDRSignalManagement/loginResponse")
    public StringResultContainer login(
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "passwordHash", targetNamespace = "")
        String passwordHash);

}
