
package org.wattalyst.services.secured;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SecuredDRSignalManagement", targetNamespace = "http://secured.services.wattalyst.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SecuredDRSignalManagement {


    /**
     * 
     * @param sensorReference
     * @param authenticationToken
     * @return
     *     returns org.wattalyst.services.secured.BaselineListResultContainer
     */
    @WebMethod
    @WebResult(name = "baselineListResultContainer", targetNamespace = "")
    @RequestWrapper(localName = "getBaselines", targetNamespace = "http://secured.services.wattalyst.org/", className = "org.wattalyst.services.secured.GetBaselines")
    @ResponseWrapper(localName = "getBaselinesResponse", targetNamespace = "http://secured.services.wattalyst.org/", className = "org.wattalyst.services.secured.GetBaselinesResponse")
    @Action(input = "http://secured.services.wattalyst.org/SecuredDRSignalManagement/getBaselinesRequest", output = "http://secured.services.wattalyst.org/SecuredDRSignalManagement/getBaselinesResponse")
    public BaselineListResultContainer getBaselines(
        @WebParam(name = "authenticationToken", targetNamespace = "")
        String authenticationToken,
        @WebParam(name = "sensorReference", targetNamespace = "")
        String sensorReference);

    /**
     * 
     * @param username
     * @param authenticationToken
     * @param signalId
     * @return
     *     returns org.wattalyst.services.secured.PiResultContainer
     */
    @WebMethod
    @WebResult(name = "piResultContainer", targetNamespace = "")
    @RequestWrapper(localName = "getPerformanceIndicator", targetNamespace = "http://secured.services.wattalyst.org/", className = "org.wattalyst.services.secured.GetPerformanceIndicator")
    @ResponseWrapper(localName = "getPerformanceIndicatorResponse", targetNamespace = "http://secured.services.wattalyst.org/", className = "org.wattalyst.services.secured.GetPerformanceIndicatorResponse")
    @Action(input = "http://secured.services.wattalyst.org/SecuredDRSignalManagement/getPerformanceIndicatorRequest", output = "http://secured.services.wattalyst.org/SecuredDRSignalManagement/getPerformanceIndicatorResponse")
    public PiResultContainer getPerformanceIndicator(
        @WebParam(name = "authenticationToken", targetNamespace = "")
        String authenticationToken,
        @WebParam(name = "signalId", targetNamespace = "")
        String signalId,
        @WebParam(name = "username", targetNamespace = "")
        String username);

    /**
     * 
     * @param username
     * @param authenticationToken
     * @param acceptanceStatus
     * @param signalId
     * @return
     *     returns org.wattalyst.services.secured.BooleanResultContainer
     */
    @WebMethod
    @WebResult(name = "booleanResultContainer", targetNamespace = "")
    @RequestWrapper(localName = "setAcceptanceStatus", targetNamespace = "http://secured.services.wattalyst.org/", className = "org.wattalyst.services.secured.SetAcceptanceStatus")
    @ResponseWrapper(localName = "setAcceptanceStatusResponse", targetNamespace = "http://secured.services.wattalyst.org/", className = "org.wattalyst.services.secured.SetAcceptanceStatusResponse")
    @Action(input = "http://secured.services.wattalyst.org/SecuredDRSignalManagement/setAcceptanceStatusRequest", output = "http://secured.services.wattalyst.org/SecuredDRSignalManagement/setAcceptanceStatusResponse")
    public BooleanResultContainer setAcceptanceStatus(
        @WebParam(name = "authenticationToken", targetNamespace = "")
        String authenticationToken,
        @WebParam(name = "signalId", targetNamespace = "")
        String signalId,
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "acceptanceStatus", targetNamespace = "")
        String acceptanceStatus);

    /**
     * 
     * @param username
     * @param description
     * @param value
     * @param authenticationToken
     * @param successStatus
     * @param signalId
     * @return
     *     returns org.wattalyst.services.secured.BooleanResultContainer
     */
    @WebMethod
    @WebResult(name = "booleanResultContainer", targetNamespace = "")
    @RequestWrapper(localName = "setPerformanceIndicator", targetNamespace = "http://secured.services.wattalyst.org/", className = "org.wattalyst.services.secured.SetPerformanceIndicator")
    @ResponseWrapper(localName = "setPerformanceIndicatorResponse", targetNamespace = "http://secured.services.wattalyst.org/", className = "org.wattalyst.services.secured.SetPerformanceIndicatorResponse")
    @Action(input = "http://secured.services.wattalyst.org/SecuredDRSignalManagement/setPerformanceIndicatorRequest", output = "http://secured.services.wattalyst.org/SecuredDRSignalManagement/setPerformanceIndicatorResponse")
    public BooleanResultContainer setPerformanceIndicator(
        @WebParam(name = "authenticationToken", targetNamespace = "")
        String authenticationToken,
        @WebParam(name = "signalId", targetNamespace = "")
        String signalId,
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "value", targetNamespace = "")
        Double value,
        @WebParam(name = "description", targetNamespace = "")
        String description,
        @WebParam(name = "successStatus", targetNamespace = "")
        String successStatus);

    /**
     * 
     * @param message
     * @param username
     * @param convenience
     * @param usefullness
     * @param authenticationToken
     * @param signalId
     * @return
     *     returns org.wattalyst.services.secured.BooleanResultContainer
     */
    @WebMethod
    @WebResult(name = "booleanResultContainer", targetNamespace = "")
    @RequestWrapper(localName = "setUserFeedback", targetNamespace = "http://secured.services.wattalyst.org/", className = "org.wattalyst.services.secured.SetUserFeedback")
    @ResponseWrapper(localName = "setUserFeedbackResponse", targetNamespace = "http://secured.services.wattalyst.org/", className = "org.wattalyst.services.secured.SetUserFeedbackResponse")
    @Action(input = "http://secured.services.wattalyst.org/SecuredDRSignalManagement/setUserFeedbackRequest", output = "http://secured.services.wattalyst.org/SecuredDRSignalManagement/setUserFeedbackResponse")
    public BooleanResultContainer setUserFeedback(
        @WebParam(name = "authenticationToken", targetNamespace = "")
        String authenticationToken,
        @WebParam(name = "signalId", targetNamespace = "")
        String signalId,
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "usefullness", targetNamespace = "")
        Integer usefullness,
        @WebParam(name = "convenience", targetNamespace = "")
        Integer convenience,
        @WebParam(name = "message", targetNamespace = "")
        String message);

    /**
     * 
     * @param startDate
     * @param baslineId
     * @param authenticationToken
     * @param endDate
     * @return
     *     returns org.wattalyst.services.secured.ValueListResultContainer
     */
    @WebMethod
    @WebResult(name = "valueListResultContainer", targetNamespace = "")
    @RequestWrapper(localName = "getBaselineData", targetNamespace = "http://secured.services.wattalyst.org/", className = "org.wattalyst.services.secured.GetBaselineData")
    @ResponseWrapper(localName = "getBaselineDataResponse", targetNamespace = "http://secured.services.wattalyst.org/", className = "org.wattalyst.services.secured.GetBaselineDataResponse")
    @Action(input = "http://secured.services.wattalyst.org/SecuredDRSignalManagement/getBaselineDataRequest", output = "http://secured.services.wattalyst.org/SecuredDRSignalManagement/getBaselineDataResponse")
    public ValueListResultContainer getBaselineData(
        @WebParam(name = "authenticationToken", targetNamespace = "")
        String authenticationToken,
        @WebParam(name = "baslineId", targetNamespace = "")
        String baslineId,
        @WebParam(name = "startDate", targetNamespace = "")
        long startDate,
        @WebParam(name = "endDate", targetNamespace = "")
        long endDate);

    /**
     * 
     * @param baselineId
     * @param values
     * @param authenticationToken
     * @return
     *     returns org.wattalyst.services.secured.BooleanResultContainer
     */
    @WebMethod
    @WebResult(name = "booleanResultContainer", targetNamespace = "")
    @RequestWrapper(localName = "uploadBaselineData", targetNamespace = "http://secured.services.wattalyst.org/", className = "org.wattalyst.services.secured.UploadBaselineData")
    @ResponseWrapper(localName = "uploadBaselineDataResponse", targetNamespace = "http://secured.services.wattalyst.org/", className = "org.wattalyst.services.secured.UploadBaselineDataResponse")
    @Action(input = "http://secured.services.wattalyst.org/SecuredDRSignalManagement/uploadBaselineDataRequest", output = "http://secured.services.wattalyst.org/SecuredDRSignalManagement/uploadBaselineDataResponse")
    public BooleanResultContainer uploadBaselineData(
        @WebParam(name = "authenticationToken", targetNamespace = "")
        String authenticationToken,
        @WebParam(name = "baselineId", targetNamespace = "")
        String baselineId,
        @WebParam(name = "values", targetNamespace = "")
        String values);

    /**
     * 
     * @param fullQualifiedName
     * @param authenticationToken
     * @return
     *     returns org.wattalyst.services.secured.StringResultContainer
     */
    @WebMethod
    @WebResult(name = "stringResultContainer", targetNamespace = "")
    @RequestWrapper(localName = "storeAndActivateSignal", targetNamespace = "http://secured.services.wattalyst.org/", className = "org.wattalyst.services.secured.StoreAndActivateSignal")
    @ResponseWrapper(localName = "storeAndActivateSignalResponse", targetNamespace = "http://secured.services.wattalyst.org/", className = "org.wattalyst.services.secured.StoreAndActivateSignalResponse")
    @Action(input = "http://secured.services.wattalyst.org/SecuredDRSignalManagement/storeAndActivateSignalRequest", output = "http://secured.services.wattalyst.org/SecuredDRSignalManagement/storeAndActivateSignalResponse")
    public StringResultContainer storeAndActivateSignal(
        @WebParam(name = "authenticationToken", targetNamespace = "")
        String authenticationToken,
        @WebParam(name = "fullQualifiedName", targetNamespace = "")
        String fullQualifiedName);

    /**
     * 
     * @param username
     * @param authenticationToken
     * @param acceptanceStatus
     * @return
     *     returns org.wattalyst.services.secured.StringListResultContainer
     */
    @WebMethod
    @WebResult(name = "stringListResultContainer", targetNamespace = "")
    @RequestWrapper(localName = "getSignalIdsByAcceptanceStatus", targetNamespace = "http://secured.services.wattalyst.org/", className = "org.wattalyst.services.secured.GetSignalIdsByAcceptanceStatus")
    @ResponseWrapper(localName = "getSignalIdsByAcceptanceStatusResponse", targetNamespace = "http://secured.services.wattalyst.org/", className = "org.wattalyst.services.secured.GetSignalIdsByAcceptanceStatusResponse")
    @Action(input = "http://secured.services.wattalyst.org/SecuredDRSignalManagement/getSignalIdsByAcceptanceStatusRequest", output = "http://secured.services.wattalyst.org/SecuredDRSignalManagement/getSignalIdsByAcceptanceStatusResponse")
    public StringListResultContainer getSignalIdsByAcceptanceStatus(
        @WebParam(name = "authenticationToken", targetNamespace = "")
        String authenticationToken,
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "acceptanceStatus", targetNamespace = "")
        List<String> acceptanceStatus);

    /**
     * 
     * @param username
     * @param authenticationToken
     * @param signalStatuses
     * @return
     *     returns org.wattalyst.services.secured.StringListResultContainer
     */
    @WebMethod
    @WebResult(name = "stringListResultContainer", targetNamespace = "")
    @RequestWrapper(localName = "getSignalIdsBySignalStatus", targetNamespace = "http://secured.services.wattalyst.org/", className = "org.wattalyst.services.secured.GetSignalIdsBySignalStatus")
    @ResponseWrapper(localName = "getSignalIdsBySignalStatusResponse", targetNamespace = "http://secured.services.wattalyst.org/", className = "org.wattalyst.services.secured.GetSignalIdsBySignalStatusResponse")
    @Action(input = "http://secured.services.wattalyst.org/SecuredDRSignalManagement/getSignalIdsBySignalStatusRequest", output = "http://secured.services.wattalyst.org/SecuredDRSignalManagement/getSignalIdsBySignalStatusResponse")
    public StringListResultContainer getSignalIdsBySignalStatus(
        @WebParam(name = "authenticationToken", targetNamespace = "")
        String authenticationToken,
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "signalStatuses", targetNamespace = "")
        List<String> signalStatuses);

    /**
     * 
     * @param username
     * @param authenticationToken
     * @param signalId
     * @return
     *     returns org.wattalyst.services.secured.DrSignalResultContainer
     */
    @WebMethod
    @WebResult(name = "drSignalResultContainer", targetNamespace = "")
    @RequestWrapper(localName = "getDetailsByUsernameAndDRSignalId", targetNamespace = "http://secured.services.wattalyst.org/", className = "org.wattalyst.services.secured.GetDetailsByUsernameAndDRSignalId")
    @ResponseWrapper(localName = "getDetailsByUsernameAndDRSignalIdResponse", targetNamespace = "http://secured.services.wattalyst.org/", className = "org.wattalyst.services.secured.GetDetailsByUsernameAndDRSignalIdResponse")
    @Action(input = "http://secured.services.wattalyst.org/SecuredDRSignalManagement/getDetailsByUsernameAndDRSignalIdRequest", output = "http://secured.services.wattalyst.org/SecuredDRSignalManagement/getDetailsByUsernameAndDRSignalIdResponse")
    public DrSignalResultContainer getDetailsByUsernameAndDRSignalId(
        @WebParam(name = "authenticationToken", targetNamespace = "")
        String authenticationToken,
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "signalId", targetNamespace = "")
        String signalId);

    /**
     * 
     * @param username
     * @param authenticationToken
     * @return
     *     returns org.wattalyst.services.secured.DrSignalListResultContainer
     */
    @WebMethod
    @WebResult(name = "drSignalListResultContainer", targetNamespace = "")
    @RequestWrapper(localName = "getNewDRSignalByUsername", targetNamespace = "http://secured.services.wattalyst.org/", className = "org.wattalyst.services.secured.GetNewDRSignalByUsername")
    @ResponseWrapper(localName = "getNewDRSignalByUsernameResponse", targetNamespace = "http://secured.services.wattalyst.org/", className = "org.wattalyst.services.secured.GetNewDRSignalByUsernameResponse")
    @Action(input = "http://secured.services.wattalyst.org/SecuredDRSignalManagement/getNewDRSignalByUsernameRequest", output = "http://secured.services.wattalyst.org/SecuredDRSignalManagement/getNewDRSignalByUsernameResponse")
    public DrSignalListResultContainer getNewDRSignalByUsername(
        @WebParam(name = "authenticationToken", targetNamespace = "")
        String authenticationToken,
        @WebParam(name = "username", targetNamespace = "")
        String username);

    /**
     * 
     * @param username
     * @param authenticationToken
     * @param signalStatus
     * @param signalId
     * @return
     *     returns org.wattalyst.services.secured.BooleanResultContainer
     */
    @WebMethod
    @WebResult(name = "booleanResultContainer", targetNamespace = "")
    @RequestWrapper(localName = "setDRSignalStatus", targetNamespace = "http://secured.services.wattalyst.org/", className = "org.wattalyst.services.secured.SetDRSignalStatus")
    @ResponseWrapper(localName = "setDRSignalStatusResponse", targetNamespace = "http://secured.services.wattalyst.org/", className = "org.wattalyst.services.secured.SetDRSignalStatusResponse")
    @Action(input = "http://secured.services.wattalyst.org/SecuredDRSignalManagement/setDRSignalStatusRequest", output = "http://secured.services.wattalyst.org/SecuredDRSignalManagement/setDRSignalStatusResponse")
    public BooleanResultContainer setDRSignalStatus(
        @WebParam(name = "authenticationToken", targetNamespace = "")
        String authenticationToken,
        @WebParam(name = "signalId", targetNamespace = "")
        String signalId,
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "signalStatus", targetNamespace = "")
        String signalStatus);

    /**
     * 
     * @param authenticationToken
     * @param signalId
     * @return
     *     returns org.wattalyst.services.secured.BooleanResultContainer
     */
    @WebMethod
    @WebResult(name = "booleanResultContainer", targetNamespace = "")
    @RequestWrapper(localName = "cancelSignal", targetNamespace = "http://secured.services.wattalyst.org/", className = "org.wattalyst.services.secured.CancelSignal")
    @ResponseWrapper(localName = "cancelSignalResponse", targetNamespace = "http://secured.services.wattalyst.org/", className = "org.wattalyst.services.secured.CancelSignalResponse")
    @Action(input = "http://secured.services.wattalyst.org/SecuredDRSignalManagement/cancelSignalRequest", output = "http://secured.services.wattalyst.org/SecuredDRSignalManagement/cancelSignalResponse")
    public BooleanResultContainer cancelSignal(
        @WebParam(name = "authenticationToken", targetNamespace = "")
        String authenticationToken,
        @WebParam(name = "signalId", targetNamespace = "")
        String signalId);

    /**
     * 
     * @param username
     * @param authenticationToken
     * @param signalId
     * @return
     *     returns org.wattalyst.services.secured.BooleanResultContainer
     */
    @WebMethod
    @WebResult(name = "booleanResultContainer", targetNamespace = "")
    @RequestWrapper(localName = "cancelSignalByUser", targetNamespace = "http://secured.services.wattalyst.org/", className = "org.wattalyst.services.secured.CancelSignalByUser")
    @ResponseWrapper(localName = "cancelSignalByUserResponse", targetNamespace = "http://secured.services.wattalyst.org/", className = "org.wattalyst.services.secured.CancelSignalByUserResponse")
    @Action(input = "http://secured.services.wattalyst.org/SecuredDRSignalManagement/cancelSignalByUserRequest", output = "http://secured.services.wattalyst.org/SecuredDRSignalManagement/cancelSignalByUserResponse")
    public BooleanResultContainer cancelSignalByUser(
        @WebParam(name = "authenticationToken", targetNamespace = "")
        String authenticationToken,
        @WebParam(name = "signalId", targetNamespace = "")
        String signalId,
        @WebParam(name = "username", targetNamespace = "")
        String username);

    /**
     * 
     * @param authenticationToken
     * @param signalId
     * @return
     *     returns org.wattalyst.services.secured.TaskListResultContainer
     */
    @WebMethod
    @WebResult(name = "taskListResultContainer", targetNamespace = "")
    @RequestWrapper(localName = "getTaskDefinitions", targetNamespace = "http://secured.services.wattalyst.org/", className = "org.wattalyst.services.secured.GetTaskDefinitions")
    @ResponseWrapper(localName = "getTaskDefinitionsResponse", targetNamespace = "http://secured.services.wattalyst.org/", className = "org.wattalyst.services.secured.GetTaskDefinitionsResponse")
    @Action(input = "http://secured.services.wattalyst.org/SecuredDRSignalManagement/getTaskDefinitionsRequest", output = "http://secured.services.wattalyst.org/SecuredDRSignalManagement/getTaskDefinitionsResponse")
    public TaskListResultContainer getTaskDefinitions(
        @WebParam(name = "authenticationToken", targetNamespace = "")
        String authenticationToken,
        @WebParam(name = "signalId", targetNamespace = "")
        String signalId);

    /**
     * 
     * @param sensorReference
     * @param description
     * @param authenticationToken
     * @param baselineType
     * @return
     *     returns org.wattalyst.services.secured.StringResultContainer
     */
    @WebMethod
    @WebResult(name = "stringResultContainer", targetNamespace = "")
    @RequestWrapper(localName = "addBaseline", targetNamespace = "http://secured.services.wattalyst.org/", className = "org.wattalyst.services.secured.AddBaseline")
    @ResponseWrapper(localName = "addBaselineResponse", targetNamespace = "http://secured.services.wattalyst.org/", className = "org.wattalyst.services.secured.AddBaselineResponse")
    @Action(input = "http://secured.services.wattalyst.org/SecuredDRSignalManagement/addBaselineRequest", output = "http://secured.services.wattalyst.org/SecuredDRSignalManagement/addBaselineResponse")
    public StringResultContainer addBaseline(
        @WebParam(name = "authenticationToken", targetNamespace = "")
        String authenticationToken,
        @WebParam(name = "description", targetNamespace = "")
        String description,
        @WebParam(name = "baselineType", targetNamespace = "")
        String baselineType,
        @WebParam(name = "sensorReference", targetNamespace = "")
        String sensorReference);

    /**
     * 
     * @param startDate
     * @param baselineId
     * @param authenticationToken
     * @param endDate
     * @return
     *     returns org.wattalyst.services.secured.StringResultContainer
     */
    @WebMethod
    @WebResult(name = "stringResultContainer", targetNamespace = "")
    @RequestWrapper(localName = "getBaselineDataAsCSV", targetNamespace = "http://secured.services.wattalyst.org/", className = "org.wattalyst.services.secured.GetBaselineDataAsCSV")
    @ResponseWrapper(localName = "getBaselineDataAsCSVResponse", targetNamespace = "http://secured.services.wattalyst.org/", className = "org.wattalyst.services.secured.GetBaselineDataAsCSVResponse")
    @Action(input = "http://secured.services.wattalyst.org/SecuredDRSignalManagement/getBaselineDataAsCSVRequest", output = "http://secured.services.wattalyst.org/SecuredDRSignalManagement/getBaselineDataAsCSVResponse")
    public StringResultContainer getBaselineDataAsCSV(
        @WebParam(name = "authenticationToken", targetNamespace = "")
        String authenticationToken,
        @WebParam(name = "baselineId", targetNamespace = "")
        String baselineId,
        @WebParam(name = "startDate", targetNamespace = "")
        long startDate,
        @WebParam(name = "endDate", targetNamespace = "")
        long endDate);

    /**
     * 
     * @param username
     * @param authenticationToken
     * @return
     *     returns org.wattalyst.services.secured.IntegerResultContainer
     */
    @WebMethod
    @WebResult(name = "integerResultContainer", targetNamespace = "")
    @RequestWrapper(localName = "getTotalEarnedCoinsByUsername", targetNamespace = "http://secured.services.wattalyst.org/", className = "org.wattalyst.services.secured.GetTotalEarnedCoinsByUsername")
    @ResponseWrapper(localName = "getTotalEarnedCoinsByUsernameResponse", targetNamespace = "http://secured.services.wattalyst.org/", className = "org.wattalyst.services.secured.GetTotalEarnedCoinsByUsernameResponse")
    @Action(input = "http://secured.services.wattalyst.org/SecuredDRSignalManagement/getTotalEarnedCoinsByUsernameRequest", output = "http://secured.services.wattalyst.org/SecuredDRSignalManagement/getTotalEarnedCoinsByUsernameResponse")
    public IntegerResultContainer getTotalEarnedCoinsByUsername(
        @WebParam(name = "authenticationToken", targetNamespace = "")
        String authenticationToken,
        @WebParam(name = "username", targetNamespace = "")
        String username);

    /**
     * 
     * @param username
     * @param authenticationToken
     * @param signalId
     * @return
     *     returns org.wattalyst.services.secured.IntegerResultContainer
     */
    @WebMethod
    @WebResult(name = "integerResultContainer", targetNamespace = "")
    @RequestWrapper(localName = "getCoinsForSignalByUsername", targetNamespace = "http://secured.services.wattalyst.org/", className = "org.wattalyst.services.secured.GetCoinsForSignalByUsername")
    @ResponseWrapper(localName = "getCoinsForSignalByUsernameResponse", targetNamespace = "http://secured.services.wattalyst.org/", className = "org.wattalyst.services.secured.GetCoinsForSignalByUsernameResponse")
    @Action(input = "http://secured.services.wattalyst.org/SecuredDRSignalManagement/getCoinsForSignalByUsernameRequest", output = "http://secured.services.wattalyst.org/SecuredDRSignalManagement/getCoinsForSignalByUsernameResponse")
    public IntegerResultContainer getCoinsForSignalByUsername(
        @WebParam(name = "authenticationToken", targetNamespace = "")
        String authenticationToken,
        @WebParam(name = "signalId", targetNamespace = "")
        String signalId,
        @WebParam(name = "username", targetNamespace = "")
        String username);

    /**
     * 
     * @param username
     * @param authenticationToken
     * @param signalStatuses
     * @return
     *     returns org.wattalyst.services.secured.DrSignalListResultContainer
     */
    @WebMethod
    @WebResult(name = "drSignalListResultContainer", targetNamespace = "")
    @RequestWrapper(localName = "getDRSignalsByUsernameAndStatuses", targetNamespace = "http://secured.services.wattalyst.org/", className = "org.wattalyst.services.secured.GetDRSignalsByUsernameAndStatuses")
    @ResponseWrapper(localName = "getDRSignalsByUsernameAndStatusesResponse", targetNamespace = "http://secured.services.wattalyst.org/", className = "org.wattalyst.services.secured.GetDRSignalsByUsernameAndStatusesResponse")
    @Action(input = "http://secured.services.wattalyst.org/SecuredDRSignalManagement/getDRSignalsByUsernameAndStatusesRequest", output = "http://secured.services.wattalyst.org/SecuredDRSignalManagement/getDRSignalsByUsernameAndStatusesResponse")
    public DrSignalListResultContainer getDRSignalsByUsernameAndStatuses(
        @WebParam(name = "authenticationToken", targetNamespace = "")
        String authenticationToken,
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "signalStatuses", targetNamespace = "")
        List<String> signalStatuses);

}
