
package org.wattalyst.services;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "DataAccessService", targetNamespace = "http://services.wattalyst.org/", wsdlLocation = "http://wattalyst.se.rwth-aachen.de:7070/DataAccessService/DataAccess?WSDL")
public class DataAccessService
    extends Service
{

    private final static URL DATAACCESSSERVICE_WSDL_LOCATION;
    private final static WebServiceException DATAACCESSSERVICE_EXCEPTION;
    private final static QName DATAACCESSSERVICE_QNAME = new QName("http://services.wattalyst.org/", "DataAccessService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://wattalyst-ci.se.rwth-aachen.de:7070/DataAccessService/DataAccess?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DATAACCESSSERVICE_WSDL_LOCATION = url;
        DATAACCESSSERVICE_EXCEPTION = e;
    }

    public DataAccessService() {
        super(__getWsdlLocation(), DATAACCESSSERVICE_QNAME);
    }

    public DataAccessService(WebServiceFeature... features) {
        super(__getWsdlLocation(), DATAACCESSSERVICE_QNAME, features);
    }

    public DataAccessService(URL wsdlLocation) {
        super(wsdlLocation, DATAACCESSSERVICE_QNAME);
    }

    public DataAccessService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DATAACCESSSERVICE_QNAME, features);
    }

    public DataAccessService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DataAccessService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns DataAccess
     */
    @WebEndpoint(name = "DataAccessPort")
    public DataAccess getDataAccessPort() {
        return super.getPort(new QName("http://services.wattalyst.org/", "DataAccessPort"), DataAccess.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DataAccess
     */
    @WebEndpoint(name = "DataAccessPort")
    public DataAccess getDataAccessPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://services.wattalyst.org/", "DataAccessPort"), DataAccess.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DATAACCESSSERVICE_EXCEPTION!= null) {
            throw DATAACCESSSERVICE_EXCEPTION;
        }
        return DATAACCESSSERVICE_WSDL_LOCATION;
    }

}
