
package org.wattalyst.services;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DataAccess", targetNamespace = "http://services.wattalyst.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DataAccess {


    /**
     * 
     * @param fullQualifiedName
     * @return
     *     returns org.wattalyst.services.LocationResultContainer
     */
    @WebMethod
    @WebResult(name = "locationResultContainer", targetNamespace = "")
    @RequestWrapper(localName = "getLocation", targetNamespace = "http://services.wattalyst.org/", className = "org.wattalyst.services.GetLocation")
    @ResponseWrapper(localName = "getLocationResponse", targetNamespace = "http://services.wattalyst.org/", className = "org.wattalyst.services.GetLocationResponse")
    @Action(input = "http://services.wattalyst.org/DataAccess/getLocationRequest", output = "http://services.wattalyst.org/DataAccess/getLocationResponse")
    public LocationResultContainer getLocation(
        @WebParam(name = "fullQualifiedName", targetNamespace = "")
        String fullQualifiedName);

    /**
     * 
     * @param fullQualifiedName
     * @return
     *     returns org.wattalyst.services.SensorResultContainer
     */
    @WebMethod
    @WebResult(name = "sensorResultContainer", targetNamespace = "")
    @RequestWrapper(localName = "getSensor", targetNamespace = "http://services.wattalyst.org/", className = "org.wattalyst.services.GetSensor")
    @ResponseWrapper(localName = "getSensorResponse", targetNamespace = "http://services.wattalyst.org/", className = "org.wattalyst.services.GetSensorResponse")
    @Action(input = "http://services.wattalyst.org/DataAccess/getSensorRequest", output = "http://services.wattalyst.org/DataAccess/getSensorResponse")
    public SensorResultContainer getSensor(
        @WebParam(name = "fullQualifiedName", targetNamespace = "")
        String fullQualifiedName);

    /**
     * 
     * @return
     *     returns org.wattalyst.services.LocationListResultContainer
     */
    @WebMethod
    @WebResult(name = "locationListResultContainer", targetNamespace = "")
    @RequestWrapper(localName = "getAllLocations", targetNamespace = "http://services.wattalyst.org/", className = "org.wattalyst.services.GetAllLocations")
    @ResponseWrapper(localName = "getAllLocationsResponse", targetNamespace = "http://services.wattalyst.org/", className = "org.wattalyst.services.GetAllLocationsResponse")
    @Action(input = "http://services.wattalyst.org/DataAccess/getAllLocationsRequest", output = "http://services.wattalyst.org/DataAccess/getAllLocationsResponse")
    public LocationListResultContainer getAllLocations();

    /**
     * 
     * @param fullQualifiedName
     * @return
     *     returns org.wattalyst.services.LocationListResultContainer
     */
    @WebMethod
    @WebResult(name = "sublocationListResultContainer", targetNamespace = "")
    @RequestWrapper(localName = "getSubLocations", targetNamespace = "http://services.wattalyst.org/", className = "org.wattalyst.services.GetSubLocations")
    @ResponseWrapper(localName = "getSubLocationsResponse", targetNamespace = "http://services.wattalyst.org/", className = "org.wattalyst.services.GetSubLocationsResponse")
    @Action(input = "http://services.wattalyst.org/DataAccess/getSubLocationsRequest", output = "http://services.wattalyst.org/DataAccess/getSubLocationsResponse")
    public LocationListResultContainer getSubLocations(
        @WebParam(name = "fullQualifiedName", targetNamespace = "")
        String fullQualifiedName);

    /**
     * 
     * @param fullQualifiedName
     * @return
     *     returns org.wattalyst.services.ValueResultContainer
     */
    @WebMethod
    @WebResult(name = "valueResultContainer", targetNamespace = "")
    @RequestWrapper(localName = "getLastValueForSensor", targetNamespace = "http://services.wattalyst.org/", className = "org.wattalyst.services.GetLastValueForSensor")
    @ResponseWrapper(localName = "getLastValueForSensorResponse", targetNamespace = "http://services.wattalyst.org/", className = "org.wattalyst.services.GetLastValueForSensorResponse")
    @Action(input = "http://services.wattalyst.org/DataAccess/getLastValueForSensorRequest", output = "http://services.wattalyst.org/DataAccess/getLastValueForSensorResponse")
    public ValueResultContainer getLastValueForSensor(
        @WebParam(name = "fullQualifiedName", targetNamespace = "")
        String fullQualifiedName);

    /**
     * 
     * @param fullQualifiedName
     * @return
     *     returns org.wattalyst.services.ValueListResultContainer
     */
    @WebMethod
    @WebResult(name = "valueListResultContainer", targetNamespace = "")
    @RequestWrapper(localName = "getValuesForSensor", targetNamespace = "http://services.wattalyst.org/", className = "org.wattalyst.services.GetValuesForSensor")
    @ResponseWrapper(localName = "getValuesForSensorResponse", targetNamespace = "http://services.wattalyst.org/", className = "org.wattalyst.services.GetValuesForSensorResponse")
    @Action(input = "http://services.wattalyst.org/DataAccess/getValuesForSensorRequest", output = "http://services.wattalyst.org/DataAccess/getValuesForSensorResponse")
    public ValueListResultContainer getValuesForSensor(
        @WebParam(name = "fullQualifiedName", targetNamespace = "")
        String fullQualifiedName);

    /**
     * 
     * @param fullQualifiedName
     * @return
     *     returns org.wattalyst.services.SensorListResultContainer
     */
    @WebMethod
    @WebResult(name = "sensorListResultContainer", targetNamespace = "")
    @RequestWrapper(localName = "getLocationSensors", targetNamespace = "http://services.wattalyst.org/", className = "org.wattalyst.services.GetLocationSensors")
    @ResponseWrapper(localName = "getLocationSensorsResponse", targetNamespace = "http://services.wattalyst.org/", className = "org.wattalyst.services.GetLocationSensorsResponse")
    @Action(input = "http://services.wattalyst.org/DataAccess/getLocationSensorsRequest", output = "http://services.wattalyst.org/DataAccess/getLocationSensorsResponse")
    public SensorListResultContainer getLocationSensors(
        @WebParam(name = "fullQualifiedName", targetNamespace = "")
        String fullQualifiedName);

    /**
     * 
     * @param sensorCategory
     * @param fullQualifiedName
     * @return
     *     returns org.wattalyst.services.SensorListResultContainer
     */
    @WebMethod
    @WebResult(name = "sensorListResultContainer", targetNamespace = "")
    @RequestWrapper(localName = "getLocationSensorsByCategory", targetNamespace = "http://services.wattalyst.org/", className = "org.wattalyst.services.GetLocationSensorsByCategory")
    @ResponseWrapper(localName = "getLocationSensorsByCategoryResponse", targetNamespace = "http://services.wattalyst.org/", className = "org.wattalyst.services.GetLocationSensorsByCategoryResponse")
    @Action(input = "http://services.wattalyst.org/DataAccess/getLocationSensorsByCategoryRequest", output = "http://services.wattalyst.org/DataAccess/getLocationSensorsByCategoryResponse")
    public SensorListResultContainer getLocationSensorsByCategory(
        @WebParam(name = "fullQualifiedName", targetNamespace = "")
        String fullQualifiedName,
        @WebParam(name = "sensorCategory", targetNamespace = "")
        String sensorCategory);

    /**
     * 
     * @param annotationValue
     * @param annotationKey
     * @param fullQualifiedName
     * @return
     *     returns org.wattalyst.services.SensorListResultContainer
     */
    @WebMethod
    @WebResult(name = "sensorListResultContainer", targetNamespace = "")
    @RequestWrapper(localName = "getLocationSensorsByAnnotation", targetNamespace = "http://services.wattalyst.org/", className = "org.wattalyst.services.GetLocationSensorsByAnnotation")
    @ResponseWrapper(localName = "getLocationSensorsByAnnotationResponse", targetNamespace = "http://services.wattalyst.org/", className = "org.wattalyst.services.GetLocationSensorsByAnnotationResponse")
    @Action(input = "http://services.wattalyst.org/DataAccess/getLocationSensorsByAnnotationRequest", output = "http://services.wattalyst.org/DataAccess/getLocationSensorsByAnnotationResponse")
    public SensorListResultContainer getLocationSensorsByAnnotation(
        @WebParam(name = "fullQualifiedName", targetNamespace = "")
        String fullQualifiedName,
        @WebParam(name = "annotationKey", targetNamespace = "")
        String annotationKey,
        @WebParam(name = "annotationValue", targetNamespace = "")
        String annotationValue);

    /**
     * 
     * @param start
     * @param fullQualifiedName
     * @param end
     * @return
     *     returns org.wattalyst.services.ValueListResultContainer
     */
    @WebMethod
    @WebResult(name = "valueListResultContainer", targetNamespace = "")
    @RequestWrapper(localName = "getValuesForSensorByRange", targetNamespace = "http://services.wattalyst.org/", className = "org.wattalyst.services.GetValuesForSensorByRange")
    @ResponseWrapper(localName = "getValuesForSensorByRangeResponse", targetNamespace = "http://services.wattalyst.org/", className = "org.wattalyst.services.GetValuesForSensorByRangeResponse")
    @Action(input = "http://services.wattalyst.org/DataAccess/getValuesForSensorByRangeRequest", output = "http://services.wattalyst.org/DataAccess/getValuesForSensorByRangeResponse")
    public ValueListResultContainer getValuesForSensorByRange(
        @WebParam(name = "fullQualifiedName", targetNamespace = "")
        String fullQualifiedName,
        @WebParam(name = "start", targetNamespace = "")
        long start,
        @WebParam(name = "end", targetNamespace = "")
        long end);

}
