
package org.wattalyst.services;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DRSignalManagement", targetNamespace = "http://services.wattalyst.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DRSignalManagement {


    /**
     * 
     * @param arg0
     * @return
     *     returns org.wattalyst.services.BaselineListResultContainer
     */
    @WebMethod
    @WebResult(name = "baselineListResultContainer", targetNamespace = "")
    @RequestWrapper(localName = "getBaselines", targetNamespace = "http://services.wattalyst.org/", className = "org.wattalyst.services.GetBaselines")
    @ResponseWrapper(localName = "getBaselinesResponse", targetNamespace = "http://services.wattalyst.org/", className = "org.wattalyst.services.GetBaselinesResponse")
    @Action(input = "http://services.wattalyst.org/DRSignalManagement/getBaselinesRequest", output = "http://services.wattalyst.org/DRSignalManagement/getBaselinesResponse")
    public BaselineListResultContainer getBaselines(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns org.wattalyst.services.PiResultContainer
     */
    @WebMethod
    @WebResult(name = "piResultContainer", targetNamespace = "")
    @RequestWrapper(localName = "getPerformanceIndicator", targetNamespace = "http://services.wattalyst.org/", className = "org.wattalyst.services.GetPerformanceIndicator")
    @ResponseWrapper(localName = "getPerformanceIndicatorResponse", targetNamespace = "http://services.wattalyst.org/", className = "org.wattalyst.services.GetPerformanceIndicatorResponse")
    @Action(input = "http://services.wattalyst.org/DRSignalManagement/getPerformanceIndicatorRequest", output = "http://services.wattalyst.org/DRSignalManagement/getPerformanceIndicatorResponse")
    public PiResultContainer getPerformanceIndicator(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns org.wattalyst.services.BooleanResultContainer
     */
    @WebMethod
    @WebResult(name = "booleanResultContainer", targetNamespace = "")
    @RequestWrapper(localName = "setAcceptanceStatus", targetNamespace = "http://services.wattalyst.org/", className = "org.wattalyst.services.SetAcceptanceStatus")
    @ResponseWrapper(localName = "setAcceptanceStatusResponse", targetNamespace = "http://services.wattalyst.org/", className = "org.wattalyst.services.SetAcceptanceStatusResponse")
    @Action(input = "http://services.wattalyst.org/DRSignalManagement/setAcceptanceStatusRequest", output = "http://services.wattalyst.org/DRSignalManagement/setAcceptanceStatusResponse")
    public BooleanResultContainer setAcceptanceStatus(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @param arg4
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns org.wattalyst.services.BooleanResultContainer
     */
    @WebMethod
    @WebResult(name = "booleanResultContainer", targetNamespace = "")
    @RequestWrapper(localName = "setPerformanceIndicator", targetNamespace = "http://services.wattalyst.org/", className = "org.wattalyst.services.SetPerformanceIndicator")
    @ResponseWrapper(localName = "setPerformanceIndicatorResponse", targetNamespace = "http://services.wattalyst.org/", className = "org.wattalyst.services.SetPerformanceIndicatorResponse")
    @Action(input = "http://services.wattalyst.org/DRSignalManagement/setPerformanceIndicatorRequest", output = "http://services.wattalyst.org/DRSignalManagement/setPerformanceIndicatorResponse")
    public BooleanResultContainer setPerformanceIndicator(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        Double arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4);

    /**
     * 
     * @param arg4
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns org.wattalyst.services.BooleanResultContainer
     */
    @WebMethod
    @WebResult(name = "booleanResultContainer", targetNamespace = "")
    @RequestWrapper(localName = "setUserFeedback", targetNamespace = "http://services.wattalyst.org/", className = "org.wattalyst.services.SetUserFeedback")
    @ResponseWrapper(localName = "setUserFeedbackResponse", targetNamespace = "http://services.wattalyst.org/", className = "org.wattalyst.services.SetUserFeedbackResponse")
    @Action(input = "http://services.wattalyst.org/DRSignalManagement/setUserFeedbackRequest", output = "http://services.wattalyst.org/DRSignalManagement/setUserFeedbackResponse")
    public BooleanResultContainer setUserFeedback(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        Integer arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        Integer arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns org.wattalyst.services.ValueListResultContainer
     */
    @WebMethod
    @WebResult(name = "valueListResultContainer", targetNamespace = "")
    @RequestWrapper(localName = "getBaselineData", targetNamespace = "http://services.wattalyst.org/", className = "org.wattalyst.services.GetBaselineData")
    @ResponseWrapper(localName = "getBaselineDataResponse", targetNamespace = "http://services.wattalyst.org/", className = "org.wattalyst.services.GetBaselineDataResponse")
    @Action(input = "http://services.wattalyst.org/DRSignalManagement/getBaselineDataRequest", output = "http://services.wattalyst.org/DRSignalManagement/getBaselineDataResponse")
    public ValueListResultContainer getBaselineData(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        long arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        long arg2);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns org.wattalyst.services.BooleanResultContainer
     */
    @WebMethod
    @WebResult(name = "booleanResultContainer", targetNamespace = "")
    @RequestWrapper(localName = "uploadBaselineData", targetNamespace = "http://services.wattalyst.org/", className = "org.wattalyst.services.UploadBaselineData")
    @ResponseWrapper(localName = "uploadBaselineDataResponse", targetNamespace = "http://services.wattalyst.org/", className = "org.wattalyst.services.UploadBaselineDataResponse")
    @Action(input = "http://services.wattalyst.org/DRSignalManagement/uploadBaselineDataRequest", output = "http://services.wattalyst.org/DRSignalManagement/uploadBaselineDataResponse")
    public BooleanResultContainer uploadBaselineData(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns org.wattalyst.services.StringResultContainer
     */
    @WebMethod
    @WebResult(name = "stringResultContainer", targetNamespace = "")
    @RequestWrapper(localName = "storeAndActivateSignal", targetNamespace = "http://services.wattalyst.org/", className = "org.wattalyst.services.StoreAndActivateSignal")
    @ResponseWrapper(localName = "storeAndActivateSignalResponse", targetNamespace = "http://services.wattalyst.org/", className = "org.wattalyst.services.StoreAndActivateSignalResponse")
    @Action(input = "http://services.wattalyst.org/DRSignalManagement/storeAndActivateSignalRequest", output = "http://services.wattalyst.org/DRSignalManagement/storeAndActivateSignalResponse")
    public StringResultContainer storeAndActivateSignal(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns org.wattalyst.services.StringListResultContainer
     */
    @WebMethod
    @WebResult(name = "stringListResultContainer", targetNamespace = "")
    @RequestWrapper(localName = "getSignalIdsByAcceptanceStatus", targetNamespace = "http://services.wattalyst.org/", className = "org.wattalyst.services.GetSignalIdsByAcceptanceStatus")
    @ResponseWrapper(localName = "getSignalIdsByAcceptanceStatusResponse", targetNamespace = "http://services.wattalyst.org/", className = "org.wattalyst.services.GetSignalIdsByAcceptanceStatusResponse")
    @Action(input = "http://services.wattalyst.org/DRSignalManagement/getSignalIdsByAcceptanceStatusRequest", output = "http://services.wattalyst.org/DRSignalManagement/getSignalIdsByAcceptanceStatusResponse")
    public StringListResultContainer getSignalIdsByAcceptanceStatus(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        List<String> arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns org.wattalyst.services.StringListResultContainer
     */
    @WebMethod
    @WebResult(name = "stringListResultContainer", targetNamespace = "")
    @RequestWrapper(localName = "getSignalIdsBySignalStatus", targetNamespace = "http://services.wattalyst.org/", className = "org.wattalyst.services.GetSignalIdsBySignalStatus")
    @ResponseWrapper(localName = "getSignalIdsBySignalStatusResponse", targetNamespace = "http://services.wattalyst.org/", className = "org.wattalyst.services.GetSignalIdsBySignalStatusResponse")
    @Action(input = "http://services.wattalyst.org/DRSignalManagement/getSignalIdsBySignalStatusRequest", output = "http://services.wattalyst.org/DRSignalManagement/getSignalIdsBySignalStatusResponse")
    public StringListResultContainer getSignalIdsBySignalStatus(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        List<String> arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns org.wattalyst.services.DrSignalResultContainer
     */
    @WebMethod
    @WebResult(name = "drSignalResultContainer", targetNamespace = "")
    @RequestWrapper(localName = "getDetailsByUsernameAndDRSignalId", targetNamespace = "http://services.wattalyst.org/", className = "org.wattalyst.services.GetDetailsByUsernameAndDRSignalId")
    @ResponseWrapper(localName = "getDetailsByUsernameAndDRSignalIdResponse", targetNamespace = "http://services.wattalyst.org/", className = "org.wattalyst.services.GetDetailsByUsernameAndDRSignalIdResponse")
    @Action(input = "http://services.wattalyst.org/DRSignalManagement/getDetailsByUsernameAndDRSignalIdRequest", output = "http://services.wattalyst.org/DRSignalManagement/getDetailsByUsernameAndDRSignalIdResponse")
    public DrSignalResultContainer getDetailsByUsernameAndDRSignalId(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns org.wattalyst.services.DrSignalListResultContainer
     */
    @WebMethod
    @WebResult(name = "drSignalListResultContainer", targetNamespace = "")
    @RequestWrapper(localName = "getNewDRSignalByUsername", targetNamespace = "http://services.wattalyst.org/", className = "org.wattalyst.services.GetNewDRSignalByUsername")
    @ResponseWrapper(localName = "getNewDRSignalByUsernameResponse", targetNamespace = "http://services.wattalyst.org/", className = "org.wattalyst.services.GetNewDRSignalByUsernameResponse")
    @Action(input = "http://services.wattalyst.org/DRSignalManagement/getNewDRSignalByUsernameRequest", output = "http://services.wattalyst.org/DRSignalManagement/getNewDRSignalByUsernameResponse")
    public DrSignalListResultContainer getNewDRSignalByUsername(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns org.wattalyst.services.BooleanResultContainer
     */
    @WebMethod
    @WebResult(name = "booleanResultContainer", targetNamespace = "")
    @RequestWrapper(localName = "setDRSignalStatus", targetNamespace = "http://services.wattalyst.org/", className = "org.wattalyst.services.SetDRSignalStatus")
    @ResponseWrapper(localName = "setDRSignalStatusResponse", targetNamespace = "http://services.wattalyst.org/", className = "org.wattalyst.services.SetDRSignalStatusResponse")
    @Action(input = "http://services.wattalyst.org/DRSignalManagement/setDRSignalStatusRequest", output = "http://services.wattalyst.org/DRSignalManagement/setDRSignalStatusResponse")
    public BooleanResultContainer setDRSignalStatus(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @param arg0
     * @return
     *     returns org.wattalyst.services.BooleanResultContainer
     */
    @WebMethod
    @WebResult(name = "booleanResultContainer", targetNamespace = "")
    @RequestWrapper(localName = "cancelSignal", targetNamespace = "http://services.wattalyst.org/", className = "org.wattalyst.services.CancelSignal")
    @ResponseWrapper(localName = "cancelSignalResponse", targetNamespace = "http://services.wattalyst.org/", className = "org.wattalyst.services.CancelSignalResponse")
    @Action(input = "http://services.wattalyst.org/DRSignalManagement/cancelSignalRequest", output = "http://services.wattalyst.org/DRSignalManagement/cancelSignalResponse")
    public BooleanResultContainer cancelSignal(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns org.wattalyst.services.BooleanResultContainer
     */
    @WebMethod
    @WebResult(name = "booleanResultContainer", targetNamespace = "")
    @RequestWrapper(localName = "cancelSignalByUser", targetNamespace = "http://services.wattalyst.org/", className = "org.wattalyst.services.CancelSignalByUser")
    @ResponseWrapper(localName = "cancelSignalByUserResponse", targetNamespace = "http://services.wattalyst.org/", className = "org.wattalyst.services.CancelSignalByUserResponse")
    @Action(input = "http://services.wattalyst.org/DRSignalManagement/cancelSignalByUserRequest", output = "http://services.wattalyst.org/DRSignalManagement/cancelSignalByUserResponse")
    public BooleanResultContainer cancelSignalByUser(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns org.wattalyst.services.TaskListResultContainer
     */
    @WebMethod
    @WebResult(name = "taskListResultContainer", targetNamespace = "")
    @RequestWrapper(localName = "getTaskDefinitions", targetNamespace = "http://services.wattalyst.org/", className = "org.wattalyst.services.GetTaskDefinitions")
    @ResponseWrapper(localName = "getTaskDefinitionsResponse", targetNamespace = "http://services.wattalyst.org/", className = "org.wattalyst.services.GetTaskDefinitionsResponse")
    @Action(input = "http://services.wattalyst.org/DRSignalManagement/getTaskDefinitionsRequest", output = "http://services.wattalyst.org/DRSignalManagement/getTaskDefinitionsResponse")
    public TaskListResultContainer getTaskDefinitions(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns org.wattalyst.services.StringResultContainer
     */
    @WebMethod
    @WebResult(name = "stringResultContainer", targetNamespace = "")
    @RequestWrapper(localName = "addBaseline", targetNamespace = "http://services.wattalyst.org/", className = "org.wattalyst.services.AddBaseline")
    @ResponseWrapper(localName = "addBaselineResponse", targetNamespace = "http://services.wattalyst.org/", className = "org.wattalyst.services.AddBaselineResponse")
    @Action(input = "http://services.wattalyst.org/DRSignalManagement/addBaselineRequest", output = "http://services.wattalyst.org/DRSignalManagement/addBaselineResponse")
    public StringResultContainer addBaseline(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns org.wattalyst.services.StringResultContainer
     */
    @WebMethod
    @WebResult(name = "stringResultContainer", targetNamespace = "")
    @RequestWrapper(localName = "getBaselineDataAsCSV", targetNamespace = "http://services.wattalyst.org/", className = "org.wattalyst.services.GetBaselineDataAsCSV")
    @ResponseWrapper(localName = "getBaselineDataAsCSVResponse", targetNamespace = "http://services.wattalyst.org/", className = "org.wattalyst.services.GetBaselineDataAsCSVResponse")
    @Action(input = "http://services.wattalyst.org/DRSignalManagement/getBaselineDataAsCSVRequest", output = "http://services.wattalyst.org/DRSignalManagement/getBaselineDataAsCSVResponse")
    public StringResultContainer getBaselineDataAsCSV(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        long arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        long arg2);

    /**
     * 
     * @param arg0
     * @return
     *     returns org.wattalyst.services.IntegerResultContainer
     */
    @WebMethod
    @WebResult(name = "integerResultContainer", targetNamespace = "")
    @RequestWrapper(localName = "getTotalEarnedCoinsByUsername", targetNamespace = "http://services.wattalyst.org/", className = "org.wattalyst.services.GetTotalEarnedCoinsByUsername")
    @ResponseWrapper(localName = "getTotalEarnedCoinsByUsernameResponse", targetNamespace = "http://services.wattalyst.org/", className = "org.wattalyst.services.GetTotalEarnedCoinsByUsernameResponse")
    @Action(input = "http://services.wattalyst.org/DRSignalManagement/getTotalEarnedCoinsByUsernameRequest", output = "http://services.wattalyst.org/DRSignalManagement/getTotalEarnedCoinsByUsernameResponse")
    public IntegerResultContainer getTotalEarnedCoinsByUsername(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns org.wattalyst.services.IntegerResultContainer
     */
    @WebMethod
    @WebResult(name = "integerResultContainer", targetNamespace = "")
    @RequestWrapper(localName = "getCoinsForSignalByUsername", targetNamespace = "http://services.wattalyst.org/", className = "org.wattalyst.services.GetCoinsForSignalByUsername")
    @ResponseWrapper(localName = "getCoinsForSignalByUsernameResponse", targetNamespace = "http://services.wattalyst.org/", className = "org.wattalyst.services.GetCoinsForSignalByUsernameResponse")
    @Action(input = "http://services.wattalyst.org/DRSignalManagement/getCoinsForSignalByUsernameRequest", output = "http://services.wattalyst.org/DRSignalManagement/getCoinsForSignalByUsernameResponse")
    public IntegerResultContainer getCoinsForSignalByUsername(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

}
