
package org.wattalyst.services;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "DRSignalManagementService", targetNamespace = "http://services.wattalyst.org/", wsdlLocation = "http://wattalyst.se.rwth-aachen.de:7070/DRSignalManagementService/DRSignalManagement?wsdl")
public class DRSignalManagementService
    extends Service
{

    private final static URL DRSIGNALMANAGEMENTSERVICE_WSDL_LOCATION;
    private final static WebServiceException DRSIGNALMANAGEMENTSERVICE_EXCEPTION;
    private final static QName DRSIGNALMANAGEMENTSERVICE_QNAME = new QName("http://services.wattalyst.org/", "DRSignalManagementService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://wattalyst-ci.se.rwth-aachen.de:7070/DRSignalManagementService/DRSignalManagement?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DRSIGNALMANAGEMENTSERVICE_WSDL_LOCATION = url;
        DRSIGNALMANAGEMENTSERVICE_EXCEPTION = e;
    }

    public DRSignalManagementService() {
        super(__getWsdlLocation(), DRSIGNALMANAGEMENTSERVICE_QNAME);
    }

    public DRSignalManagementService(WebServiceFeature... features) {
        super(__getWsdlLocation(), DRSIGNALMANAGEMENTSERVICE_QNAME, features);
    }

    public DRSignalManagementService(URL wsdlLocation) {
        super(wsdlLocation, DRSIGNALMANAGEMENTSERVICE_QNAME);
    }

    public DRSignalManagementService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DRSIGNALMANAGEMENTSERVICE_QNAME, features);
    }

    public DRSignalManagementService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DRSignalManagementService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns DRSignalManagement
     */
    @WebEndpoint(name = "DRSignalManagementPort")
    public DRSignalManagement getDRSignalManagementPort() {
        return super.getPort(new QName("http://services.wattalyst.org/", "DRSignalManagementPort"), DRSignalManagement.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DRSignalManagement
     */
    @WebEndpoint(name = "DRSignalManagementPort")
    public DRSignalManagement getDRSignalManagementPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://services.wattalyst.org/", "DRSignalManagementPort"), DRSignalManagement.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DRSIGNALMANAGEMENTSERVICE_EXCEPTION!= null) {
            throw DRSIGNALMANAGEMENTSERVICE_EXCEPTION;
        }
        return DRSIGNALMANAGEMENTSERVICE_WSDL_LOCATION;
    }

}
